export const NavigationKey = {
  STACK_AUTH: 'Auth',
  SCREEN_LOGIN: 'Login',
  DRAWER_MAIN: 'MainDrawer',
  STACK_LANDING: 'Landing',
  SCREEN_LANDING: 'Main',
  SCREEN_PLAN_SCHEDULE_LOADER: 'PlanScheduleLoader',
  SCREEN_VIEW_SCHEDULE: 'ViewSchedule',
  SCREEN_PLAN_SCHEDULE: 'PlanSchedule',
  SCREEN_SUBMIT_SCHEDULE_SUCCESS: 'SubmitScheduleSuccess',
  SCREEN_MANAGE_TEAM: 'ManageTeam',
  SCREEN_WORK_SCHEDULE_REQUESTS: 'WorkScheduleRequests',
  SCREEN_DETAILED_SCHEDULE_REQUEST: 'DetailedScheduleRequest',
  SCREEN_DECLINE_WORK_SCHEDULE_SUCCESS: 'DeclineWorkScheduleSuccess',
  SCREEN_DECLINE_WORK_SCHEDULE: 'DeclineWorkSchedule',
  SCREEN_UNASSIGNED_EMPLOYEE_CREDITS: 'UnassignedEmployeeCredits',
  SCREEN_ASSIGN_CREDITS: 'AssignCredits',
  SCREEN_WORKFORCE_MONITORING: 'WorkforceMonitoring',
  SCREEN_REQUEST_REPORT: 'RequestReport',
  SCREEN_REQUEST_REPORT_SUCCESS: 'RequestReportSuccess',
  SCREEN_BOOK_WORKSTATION: 'BookWorkstation',
  SCREEN_WORKSTATION_SELECT: 'WorkStationSelect',
  SCREEN_UPCOMING_RESERVATIONS: 'UpcomingReservations',
  SCREEN_WORK_FROM_BRANCH: 'WorkFromBranchScreen',
  SCREEN_WORK_FROM_BRANCH_VIEW: 'WorkFromBranchViewScreen',
  SCREEN_BOOKING_WFO_SUCCESS: 'BookingWFOSuccessScreen',
  SCREEN_BOOKING_WFB_SUCCESS: 'BookingWFBSuccessScreen',
  SCREEN_WFB_SELECT_DATE: 'WFBSelectDateScreen',
  SCREEN_WS_SELECT_DATE: 'WorkstationSelectDateScreen',
  SCREEN_PARKING_SUCCESS: 'ParkingSuccessScreen',
  SCREEN_RESERVE_PARKING: 'ReserveParking',
  SCREEN_PS_SELECT_DATE: 'ParkingSelectDateScreen',
  SCREEN_QR_SCAN: 'QRScanScreen',
  SCREEN_QR_UPLOAD: 'UploadQRScreen',
  SCREEN_CHECK_IN_OUT_CONFIRM: 'CheckInOutConfirmScreen',
  SCREEN_PARKING_SELECT: 'ParkingSelect',
  SCREEN_PARKING_UPCOMING_RESERVATIONS: 'ParkingUpcomingReservations',
  SCREEN_TRANSFER_PARKING: 'TransferParking',
  SCREEN_TRANSFER_PARKING_EMPLOYEE_SELECTION:
    'TransferParkingEmployeeSelection',
  SCREEN_TRANSFER_PARKING_SUCCESS: 'TransferParkingSuccess',
  SCREEN_TRANSFER_PARKING_DATE_SELECTION: 'TransferParkingDateSelection',
  SCREEN_NOTIFICATION_LIST: 'NotificationList',
} as const;
